// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://equbkfdztjvdgvckharp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxdWJrZmR6dGp2ZGd2Y2toYXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzMzNTMsImV4cCI6MjA3NDAwOTM1M30.oYFWKsryeV7k1cvXPS61Gt_dfHQYX07DeDISG2FJlQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});